services:
  python-venv:
    image: python-uv-env:latest
    container_name: python-venv
    build:
      context: . # 上下文路径为当前目录, 如果使用dockerfile构建，则image是构建的镜像名
      dockerfile: Dockerfile # 指定 Dockerfile 的相对路径
    environment:
      TZ: "UTC" # 设置时区为 UTC
    ports:
      - "10022:22" # 映射主机的 10222 端口到容器的 22 端口,用于 SSH 连接
      - "8000:8000"
      - "8070:8070"
      - "8080:8080"
      - "8090:8090"
    volumes:
      # 挂载 SSH 密钥（仅挂载必要文件）
      - "./ssh-keys/id_rsa:/tmp/host-ssh/id_rsa:ro"
      - "./ssh-keys/id_rsa.pub:/tmp/host-ssh/id_rsa.pub:ro"
    privileged: true # 开启特权模式
    stdin_open: true # 保持容器的标准输入打开
    tty: true # 分配伪终端
    networks:
      - common-network # 使用共享网络

  redis:
    image: "redis:6.0.16"
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      TZ: "UTC"
    command: redis-server --requirepass 123456
    volumes:
      - "./infras/redis/data:/data"
      - "./infras/redis/redis.conf:/etc/redis/redis.conf"
    networks:
      - common-network

# 定义共享网络
networks:
  common-network:
    name: common-network
    driver: bridge
